routes/web.php
Route::get('/questions-section/{section}', 'QuestionsController@section')->name('questions.section');
Route::get('/news-home', 'NewsController@home')->name('news.home');
Route::get('/section/{section}', 'NewsController@section')->name('section');

Route::get('/promo', 'PromoController@index')->name('promo.index');

//news routes
Route::get('/news/create', 'NewsController@create')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('news.create');
Route::post('/news', 'NewsController@store')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('news.store');
Route::get('/news', 'NewsController@index')->name('news.index');
Route::get('/news/trending', 'NewsController@trending')->name('news.trending');
Route::patch('/news/{news}', 'NewsController@update')
		->middleware('auth')->name('news.update');
Route::delete('/news/{news}', 'NewsController@destroy')->middleware('auth')->name('news.destroy');
Route::get('/news/{news}/edit', 'NewsController@edit')->middleware('auth')->name('news.edit');
Route::get('/news/{news}/comments', 'CommentController@index')->name('comments.index');
Route::post('/news/{news}/comments', 'CommentController@store')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('comments.store');
Route::post('/update-comments/{comment}', 'CommentController@update')
		->middleware('auth')->name('comments.update');
Route::delete('/comments/{comment}', 'CommentController@destroy')
		->middleware('auth')->name('comments.destroy');

Route::get('/news-report/{news}', 'NewsController@createReport')
		->middleware('auth')->name('news.report');
Route::get('/comments-report/{comment}', 'CommentController@createReport')
		->middleware('auth')->name('comments.report');

Route::get('/news/{news}/login', 'NewsController@loginToComment')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('news.login');
Route::get('/news/{news}/{slug}', 'NewsController@show')->name('news.show');

// statuses routes
Route::get('/statuses/{status}', 'StatusController@show')->name('statuses.show');
Route::post('/statuses', 'StatusController@store')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('statuses.store');
Route::patch('/statuses/{status}', 'StatusController@update')
		->middleware('auth')->name('statuses.update');
Route::delete('/statuses/{status}', 'StatusController@destroy')
		->middleware('auth')->name('statuses.destroy');
Route::get('/statuses/{status}/edit', 'StatusController@edit')
		->middleware('auth')->name('statuses.edit');
Route::get('/statuses/{status}/responses', 'ResponseController@index')->name('responses.index');
Route::post('/statuses/{status}/responses', 'ResponseController@store')
		->middleware('auth', 'user-not-banned')->name('responses.store');
Route::post('/update-responses/{response}', 'ResponseController@update')
		->middleware('auth')->name('responses.update');
Route::delete('/responses/{response}', 'ResponseController@destroy')
		->middleware('auth')->name('responses.destroy');

Route::get('/statuses-report/{status}', 'StatusController@createReport')
		->middleware('auth')->name('statuses.report');
Route::get('/responses-report/{response}', 'ResponseController@createReport')
		->middleware('auth')->name('responses.report');


Route::middleware('auth')->group(function() {
	//likes routes
	Route::post('/threads/{thread}/likes', 'LikeController@likeThread');
	Route::delete('/threads/{thread}/likes', 'LikeController@unlikeThread');
	Route::post('/threads/{thread}/dislikes', 'LikeController@dislikeThread');
	Route::delete('/threads/{thread}/dislikes', 'LikeController@undislikeThread');

	Route::post('/questions/{question}/likes', 'LikeController@likeQuestion');
	Route::delete('/questions/{question}/likes', 'LikeController@unlikeQuestion');
	Route::post('/questions/{question}/dislikes', 'LikeController@dislikeQuestion');
	Route::delete('/questions/{question}/dislikes', 'LikeController@undislikeQuestion');

	Route::post('/news/{news}/likes', 'LikeController@likeNews');
	Route::delete('/news/{news}/likes', 'LikeController@unlikeNews');
	Route::post('/news/{news}/dislikes', 'LikeController@dislikeNews');
	Route::delete('/news/{news}/dislikes', 'LikeController@undislikeNews');

	Route::post('/statuses/{status}/likes', 'LikeController@likeStatus');
	Route::delete('/statuses/{status}/likes', 'LikeController@unlikeStatus');
	Route::post('/statuses/{status}/dislikes', 'LikeController@dislikeStatus');
	Route::delete('/statuses/{status}/dislikes', 'LikeController@undislikeStatus');

	Route::post('/replies/{reply}/likes', 'LikeController@likeReply');
	Route::delete('/replies/{reply}/likes', 'LikeController@unlikeReply');
	Route::post('/replies/{reply}/dislikes', 'LikeController@dislikeReply');
	Route::delete('/replies/{reply}/dislikes', 'LikeController@undislikeReply');

	Route::post('/answers/{answer}/likes', 'LikeController@likeAnswer');
	Route::delete('/answers/{answer}/likes', 'LikeController@unlikeAnswer');
	Route::post('/answers/{answer}/dislikes', 'LikeController@dislikeAnswer');
	Route::delete('/answers/{answer}/dislikes', 'LikeController@undislikeAnswer');

	Route::post('/comments/{comment}/likes', 'LikeController@likeComment');
	Route::delete('/comments/{comment}/likes', 'LikeController@unlikeComment');
	Route::post('/comments/{comment}/dislikes', 'LikeController@dislikeComment');
	Route::delete('/comments/{comment}/dislikes', 'LikeController@undislikeComment');

	Route::post('/responses/{response}/likes', 'LikeController@likeResponse');
	Route::delete('/responses/{response}/likes', 'LikeController@unlikeResponse');
	Route::post('/responses/{response}/dislikes', 'LikeController@dislikeResponse');
	Route::delete('/responses/{response}/dislikes', 'LikeController@undislikeResponse');

	// subscription routes
	Route::post('/threads/{thread}/subscriptions', 'SubscriptionController@subscribeThread');
	Route::delete('/threads/{thread}/subscriptions', 'SubscriptionController@unsubscribeThread');

	Route::post('/questions/{question}/subscriptions', 'SubscriptionController@subscribeQuestion');
	Route::delete('/questions/{question}/subscriptions', 'SubscriptionController@unsubscribeQuestion');

	Route::post('/news/{news}/subscriptions', 'SubscriptionController@subscribeNews');
	Route::delete('/news/{news}/subscriptions', 'SubscriptionController@unsubscribeNews');

	// notification route
	Route::get('/notifications', 'UserNotificationController@allNotifications');
	Route::get('/delete-all-notifications', 'UserNotificationController@deleteAll')
			->name('delete.all.notifications');
	Route::delete('/notifications/{notification}', 'UserNotificationController@destroy');

	// appeal routes
	Route::get('/appeal', 'AppealController@index')->name('appeals.index');
	Route::get('/appeal/create', 'AppealController@create')->name('appeals.create');
	Route::post('/appeal', 'AppealController@store')->name('appeals.store');
	Route::delete('/appeal/{appeal}', 'AppealController@destroy')->name('appeals.destroy');

});


// report routes
Route::post('/report', 'ReportController@store')->middleware('auth')->name('reports.store');
Route::get('/report', 'ReportController@index')
	->middleware('auth', 'admin')->name('reports.index');
Route::delete('/report/{report}', 'ReportController@destroy')
	->middleware('auth', 'admin')->name('reports.destroy');
Route::post('report-blocked/{report}', 'ReportController@update')
	->middleware('auth', 'admin')->name('reports.blocked');

// management routes
Route::prefix('manage')
	->middleware('auth', 'admin')
	->group(function() {
	Route::get('/', 'ManageController@index')->name('manage.index');
	Route::get('/users', 'ManageUsersController@index')->name('manage.users');
	Route::get('/users/search', 'ManageUsersController@search')->name('manage.users.search');
	Route::get('/dashboard', 'ManageController@dashboard')->name('manage.dashboard');
	//sections routes
	Route::get('/sections', 'SectionsController@index')->name('sections.index');
	Route::post('/sections', 'SectionsController@store')->name('sections.store');
	Route::get('/sections/{section}/edit', 'SectionsController@edit')->name('sections.edit');
	Route::patch('/sections/{section}', 'SectionsController@update')->name('sections.update');
	Route::delete('/sections/{section}', 'SectionsController@destroy')->name('sections.destroy');
});
	
Route::middleware('auth', 'admin')
	->group(function() {
	//lock contents routes
	Route::post('/locked-threads/{thread}', 'LockedContentsController@lockThread')
			->name('locked-threads.store');
	Route::delete('/locked-threads/{thread}', 'LockedContentsController@unlockThread')
			->name('locked-threads.destroy');

	Route::post('/locked-questions/{question}', 'LockedContentsController@lockQuestion')
			->name('locked-questions.store');
	Route::delete('/locked-questions/{question}', 'LockedContentsController@unlockQuestion')
			->name('locked-questions.destroy');

	Route::post('/locked-news/{news}', 'LockedContentsController@lockNews')
			->name('locked-news.store');
	Route::delete('/locked-news/{news}', 'LockedContentsController@unlockNews')
			->name('locked-news.destroy');

	// block contents routes
	Route::post('/blocked-threads/{thread}', 'BlockedContentsController@blockThread')
			->name('blocked-threads.store');
	Route::delete('/blocked-threads/{thread}', 'BlockedContentsController@unblockThread')
			->name('blocked-threads.destroy');

	Route::post('/blocked-questions/{question}', 'BlockedContentsController@blockQuestion')
			->name('blocked-questions.store');
	Route::delete('/blocked-questions/{question}', 'BlockedContentsController@unblockQuestion')
			->name('blocked-questions.destroy');

	Route::post('/blocked-news/{news}', 'BlockedContentsController@blockNews')
			->name('blocked-news.store');
	Route::delete('/blocked-news/{news}', 'BlockedContentsController@unblockNews')
			->name('blocked-news.destroy');

	Route::post('/blocked-statuses/{status}', 'BlockedContentsController@blockStatus')

app/Thread.php
<?php

namespace App;

use App\Commonables;
use App\Dislike;
use App\Events\ThreadReceivedNewReply;
use App\Likable;
use App\Like;
use App\Notifications\ThreadWasUpdated;
use App\RecordsVisits;
use App\Reply;
use App\Section;
use App\Subscription;
use App\User;
use Illuminate\Database\Eloquent\Model;

class Thread extends Model
{
    use Likable, RecordsActivity, RecordsVisits, Commonables;

    /**
     * The relationships to always eager-load.
     *
     * @var array
     */
    protected $with = ['creator'];

    protected $fillable = [
        'user_id', 'section_id', 'title', 
        'slug', 'body', 'locked', 'pinned', 
        'blocked', 'featured_thread', 'featured_home', 
        'image1_path', 'image2_path', 
        'sponsored_home', 'thumbnail_path'
    ];

    protected $appends = [
       'isLiked', 'isDisliked', 'isSubscribedTo',
        'image1', 'image2', 'thumbnail'
    ];

    protected $casts = [
        'locked' => 'boolean',
        'blocked' => 'boolean',
        'pinned' => 'boolean',
        'featured_thread' => 'boolean',
        'featured_home' => 'boolean'
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(function ($builder) {
            $builder->withCount('replies')
                ->withCount('likes')
                ->withCount('dislikes');
        });
        
        static::creating(function ($thread) {
            Reputation::award($thread->creator, Reputation::THREAD_WAS_CREATED);
        });

        static::deleting(function ($thread) {
            $thread->replies->each->delete();

            Reputation::reduce($thread->creator, Reputation::THREAD_WAS_CREATED);
        });
    }
	
    public function path()
    {
    	return "/threads/{$this->id}";
    }

    public function showPath()
    {
        return "/threads/{$this->id}/{$this->slug}";
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function replies()
    {
        return $this->hasMany(Reply::class)->withCount('likes')->withCount('dislikes');
    }

    public function section()
    {
        return $this->belongsTo(Section::class);
    }

    public function addReply($reply)
    {
        $reply = $this->replies()->create($reply);

        // event to handle lot of things like sending
        // notification to thread subscribers and mentioned users
        event(new ThreadReceivedNewReply($reply));

        // notify thread owner if others leave a reply
        if($reply->user_id != $this->user_id) {
            $this->creator->notify(new ThreadWasUpdated($this, $reply));
        }

        return $reply;
    }

    public function lock()
    {
        $this->update(['locked' => true]);
    }

    public function unlock()
    {
        $this->update(['locked' => false]);
    }

    public function block()
    {
        $this->update(['blocked' => true]);

        $this->update(['locked' => true]);
    }

    public function unblock()
    {
        $this->update(['blocked' => false]);

        $this->update(['locked' => false]);
    }

    public function featureThread()
    {
        $this->update(['featured_thread' => true]);
    }

    public function unfeatureThread()
    {
        $this->update(['featured_thread' => false]);
    }

    public function featureHome()
    {
        $this->update(['featured_home' => true]);
    }

    public function unfeatureHome()
    {
        $this->update(['featured_home' => false]);
    }

    public function sponsorHome()
    {
        $this->update(['sponsored_home' => true]);
    }

    public function unsponsorHome()
    {
        $this->update(['sponsored_home' => false]);
    }

    public function notifySubscribers($reply) 
    {
        foreach ($this->subscriptions as $subscription) {
            if ($subscription->user->id != $reply->user_id) {
                $subscription->user->notify(new ThreadWasUpdated($this, $reply));
            }
        }
    }

    public function scopeFilter($query, $filter)
    {
        return $filter->apply($query);
    }

    // subscriptions methods
    public function subscriptions()
    {
        return $this->morphMany(Subscription::class, 'subscribed');
    }

    public function subscribe()
    {
        $attributes = ['user_id' => auth()->id()];

        if (! $this->subscriptions()->where($attributes)->exists()) {
            $this->subscriptions()->create($attributes);
        }
    }

    public function unsubscribe()
    {
        $this->subscriptions()->where(['user_id' => auth()->id()])->get()->each->delete();
    }

    public function isSubscribedTo()
    {
        return $this->subscriptions()->where('user_id', auth()->id())->exists();
    }

    public function getIsSubscribedToAttribute()
    {
        return $this->isSubscribedTo();
    }


    public function hasUpdateFor()
    {
        $key = auth()->user()->visitedContentsCacheKey($this);

        if($this->replies()->exists()) {
            $lastReply = $this->replies()->latest()->first();
            if($lastReply->user_id != auth()->id()) {
                return $lastReply->updated_at > cache($key);
            }
        }
    }

    public function getBodyAttribute($body)
    {
        if($this->blocked) {
            return '<p style="color:red;">This thread has been blocked.</p>';
        }
        return \Purify::clean(ucfirst($body));
    }

}

resources/views/threads/_body_footer.blade.php
<div class="level is-marginless has-border-top-bottom p-5 is-size-7">
	<div class="level-left">
		<span class="p-l-20" v-text="likesCount">
			{{-- {{ $thread->likes_count }} {{ str_plural('Like', $thread->likes_count) }} --}}
		</span>
		<span class="p-l-20" v-text="dislikesCount"></span>
		<span class="p-l-20">
			<span v-text="repliesCount"></span>
		</span>
	</div>

	@include('partials.share_buttons', ['title' => $thread->title])	
</div>

@if(Auth()->check())
	<div class="level is-marginless p-5 is-size-6 has-border-bottom">
		<div class="level-left">
			<like :model="{{ $thread }}" @liked="likeCounter"
				:model-route="'/threads/'"
				:like-type="'Like'"
				:dislike-type="'Dislike'">
			</like>
			<span v-if="isConfirmed" v-cloak>
				<a href="#newreply-textarea" class="m-l-10 m-b-5 button is-small is-outlined is-link"><i class="fa fa-reply is-size-6 m-r-5"></i>Reply</a>
			</span>
		</div>
		<div class="level-right m-0">
			<subscribe-button 
				:data="{{ json_encode($thread->isSubscribedTo) }}" 
				:modelpath="{{ json_encode($thread->path()) }}"
				v-if="! authorize('owns', thread)">
			</subscribe-button>

			<a href="{{ route('threads.report', $thread) }}" class="button is-small is-danger is-outlined m-l-5">Report</a>
		</div>
	</div>

	@can('update', $thread)
		<div class="level is-marginless p-5 is-size-6">
			<div class="level-left m-0 p-b-5">
				<admin-actions routename="threads/" 
					:model="{{ $thread }}" 
					:featured="{{ json_encode($thread->featured_thread) }}">
				</admin-actions>
			</div>
			<div class="level-right m-0">
				<form method="POST" action="{{ route('threads.destroy', $thread) }}" class="m-l-10">
					@csrf
					{{ method_field('DELETE') }}
					<a class="button is-small is-link is-outlined" href="{{ route('threads.edit', $thread) }}">Edit</a>

					@include('partials.confirm_delete')

				</form>
			</div>
		</div>
	@endcan
@endif

resources/views/threads/add_reply.blade.php
<div class="m-10">
	<form method="POST" action="{{ route('replies.store', $thread->id) }}">
		@csrf

        <div class="field">
            <div class="control">
                <textarea
                    class="textarea {{ $errors->has('body') ? ' is-danger' : '' }}" 
                    id="body" name="body" rows="1" 
                    placeholder="Add a reply" required>
                    {{ old('body') }}
                </textarea>
                    
                @if ($errors->has('body'))
                    <p class="help is-danger">
                        <strong>{{ $errors->first('body') }}</strong>
                    </p>
                @endif
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button type="submit" class="button is-link is-small">
                    Reply
                </button>
            </div>
        </div>

	</form>
</div>

resources/views/threads/body.blade.php
	{{-- SHOWING MAIN THREAD--}}
<div class="has-border"> 
	{{-- main thread heading --}}
	@include('threads._body_heading')

	<div class="p-10">
		<p class="has-text-centered" v-if="image1">
			<figure class="image">
				<img :src="image1" alt="">
			</figure>
		</p>

		<p class="is-size-6 m-b-15 m-t-15" v-html="body"></p>
		
		<p class="has-text-centered" v-if="image2">
			<figure class="image">
				<img :src="image2" alt="">
			</figure>
		</p>
	</div>
	{{-- main thread footer --}}
	@include('threads._body_footer')

</div> {{-- end of main thread title and body --}}




	{{-- EDITING MAIN THREAD --}}
{{-- <div class="has-border" v-if="editing" v-cloak> 	
	<div class="p-10">
		<div class="field">
			<label for="title" class="label">Title: </label>
			<div class="control">
				<input type="text" name="title" class="input" v-model="form.title">
			</div>
		</div>

		<div class="field">
			<label for="body" class="label">Body: </label>
			<div class="control">

				<div id="updatethread-textarea">
					<trumbowyg v-model="form.body" 
						:config="config" class="form-control" 
						required></trumbowyg>
				</div>
			</div>
		</div>

		<div class="field">
			<p class="is-underline"><strong>change Image/s</strong></p>
			<p class="is-size-7">
				<span class="is-red">NB: </span>Only jpg, jpeg, png, gif, svg images with max-size:2MB are allowed.
			</p>
			<div class="control">
				<label for="image1">Change Image 1.</label>
				<input type="file" name="image1" accept="image/*">
			</div>
			<div class="control">
				<label for="image2">Change Image 2.</label>
				<input type="file" name="image2" accept="image/*">
			</div>
		</div>

		<div v-if="errors" v-for="error in errors">
            <div v-for="err in error">
                <p class="help is-danger" v-text="err"></p>
            </div>
        </div>

	</div>

	<div class="level is-marginless has-border-top-bottom p-5 is-size-7">
	@can('update', $thread)
		<div class="level-right">
			<button class="button is-primary is-small m-l-10" @click="update">Update</button>
			<button class="button is-danger is-small m-l-10" @click="cancel">Cancel</button>
		</div>
	@endcan
	
</div>

</div> --}} {{-- end of editing --}}

resources/views/threads/edit.blade.php
@extends('layouts.app')

@section('title', 'NaijaNewsForum | Edit Thread')

@section('styles')
	<link href="{{ asset('css/vendor/trumbowyg.min.css') }}" rel="stylesheet">
	{{-- <link href="{{ asset('vendor/trumbowyg/dist/plugins/colors/ui/trumbowyg.colors.css') }}" rel="stylesheet"> --}}
@endsection

@section('content')
{{-- <create-thread inline-template> --}}
	<div class="box">
		
		<form method="POST" action="{{ route('threads.update', $thread) }}" enctype="multipart/form-data">
	        @csrf
	        {{ method_field('patch') }}

	        <p class="is-size-4 has-border-bottom-2 m-b-20 has-text-centered">Edit Thread</p>
	        
	        <div class="field">
	            <label for="title" class="label">Topic:</label>
	            <div class="control">
	                <input type="text" 
	                    class="input {{ $errors->has('title') ? ' is-danger' : '' }}" 
	                    id="title" name="title" maxlength="100"
	                    value="{{ old('title', $thread->title) }}" required autofocus>

	                @if ($errors->has('title'))
	                    <p class="help is-danger">
	                        {{ $errors->first('title') }}
	                    </p>
	                @endif
	            </div>
	        </div>

	        <div class="field">
	            <label for="body" class="label">Body of Thread:</label>
	            <div class="control">
					<div id="create-textarea">
		                <textarea
		                    class="textarea {{ $errors->has('body') ? ' is-danger' : '' }}" 
		                    id="body" name="body" rows="1" 
		                    placeholder="Enter Body of your Thread here" required>
		                    {{ old('body', $thread->body) }}
		                </textarea>
		            </div>
	                    
	                @if ($errors->has('body'))
	                    <p class="help is-danger">
	                        {{ $errors->first('body') }}
	                    </p>
	                @endif
	            </div>
	        </div>

			<div class="field">
				<p class="is-underline"><strong>Add/Change Image/s</strong></p>
				<p class="is-size-7">
					<span class="is-red">NB: </span>Only jpg, jpeg, png, gif, svg images with max-size:4MB are allowed.
				</p>
				<div class="control">
					<label for="image1">Add/Change Image 1.</label>
					<input type="file" name="image1" accept="image/*">
				</div>
				<div class="control">
					<label for="image2">Add/Change Image 2.</label>
					<input type="file" name="image2" accept="image/*">
				</div>

				<div class="control" v-if="isAdmin" v-cloak>
					<label class="checkbox has-text-danger">
                        <input type="checkbox" name="delete_image1"> 
                        Delete Image 1
                    </label>
                    <label class="checkbox has-text-danger">
                        <input type="checkbox" name="delete_image2"> 
                        Delete Image 2
                    </label>
				</div>

				@if ($errors->has('image1'))
                    <p class="help is-danger">
                        {{ $errors->first('image1') }}
                    </p>
                @endif

                @if ($errors->has('image2'))
                    <p class="help is-danger">
                        {{ $errors->first('image2') }}
                    </p>
                @endif
			</div>

	        <div class="field">
	            <div class="control">
	                <button type="submit" class="button is-link">
	                    Update Thread
	                </button>
	            </div>
	        </div>

	    </form>

	</div>
{{-- </create-thread> --}}
@endsection

@section('scripts')
	<script src="{{ asset('js/vendor/trumbowyg.min.js') }}"></script>
	
	{{-- Import Trumbowyg colors JS at the end of.. --}}
	{{-- <script src="{{ asset('vendor/trumbowyg/dist/plugins/colors/trumbowyg.colors.min.js') }}"></script> --}}

	<script>
		$('textarea').trumbowyg({
			autogrow: true,
			autogrowOnEnter: true,
			btns: [
				['strong', 'em', 'del'],
				['superscript', 'subscript'],
				// ['formatting'],
				// ['foreColor'],
				['link'],
				['insertImage'],
				['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
				// ['horizontalRule']
			]
		});
	</script>
@endsection

resources/views/threads/section_thread.blade.php
	{{-- Main thread title and body --}}
<div class="has-border m-b-20"> 
	<h2 class="is-size-5 p-5 m-l-10 is-darkgreen has-text-centered">
		<a class="is-darkgreen" href="{{ $thread->showPath() }}">{{ $thread->title }}</a>
	</h2>

	<div class="media has-border-top-bottom p-5">
		<figure class="media-left">
			<p class="image is-32x32">
				<a href="{{ route('profile', $thread->creator) }}">
					<img src="{{ $thread->creator->thumbnail }}" alt="">
				</a>
			</p>
		</figure>
		<div class="media-content">
			<div class="level is-mobile is-marginless">
				<div class="level-left">
					<span class="is-size-7">
						<strong>
							<a href="{{ route('profile', $thread->creator) }}">
								{{ $thread->creator->username }}
							</a> <span>({{ $thread->creator->reputation }} xp)</span>
						</strong><br>
					</span>
				</div>
				<div class="level-right">
					<span class="is-size-7">
						<strong>{{ $thread->created_at->diffForHumans() }}</strong>
					</span>
				</div>
			</div>
			<p>
				<span class="is-size-7">
					<strong>
						{{ str_limit($thread->creator->title, 50) }}
					</strong>
				</span>
			</p>
		</div>
	</div> {{-- end of media --}}

	<div class="has-border-top">
		<span class="is-size-7">
			<span class="p-l-10">
				{{ $likesCount = $thread->likes_count }} {{ str_plural('Like', $likesCount) }}
			</span>
			<span class="p-l-10">
				{{ $thread->replies_count }} {{ str_plural('reply', $thread->replies_count) }}
			</span>
		</span>
	</div>
</div> {{-- end of main thread title and body --}}

resources/views/threads/subscription_thread.blade.php
	{{-- Main thread title and body --}}
<div class="has-border m-b-20"> 
	@if($thread->hasUpdateFor())
		<h1 class="is-size-5 has-text-justified p-5 m-l-10">
			<a class="is-darkgreen" href="{{ $thread->showPath() }}">
				<strong>{{ $thread->title }}</strong><i class="is-upated-note m-l-5">updated</i>
			</a>
		</h1>
	@else
		<h1 class="is-size-5 has-text-justified p-5 m-l-10">
			<a class="is-darkgreen" href="{{ $thread->showPath() }}">{{ $thread->title }}</a></h1>
	@endif

	<div class="media has-border-top-bottom p-5">
		<figure class="media-left">
			<p class="image is-32x32">
				<a href="{{ route('profile', $thread->creator) }}">
					<img src="{{ $thread->creator->thumbnail }}" alt="avatar">
				</a>
			</p>
		</figure>
		<div class="media-content">
			<div class="level is-mobile is-marginless">
				<div class="level-left">
					<span class="is-size-7">
						<strong>
							<a href="{{ route('profile', $thread->creator) }}">
								{{ $thread->creator->username }}
							</a> <span>({{ $thread->creator->reputation }} xp)</span>
						</strong><br>
					</span>
				</div>
				<div class="level-right">
					<span class="is-size-7">
						<strong>{{ $thread->created_at->diffForHumans() }}</strong>
					</span>
				</div>
			</div>
			<p>
				<span class="is-size-7">
					<strong>
						{{ str_limit($thread->creator->title, 50) }}
					</strong>
				</span>
			</p>
		</div>
	</div> {{-- end of media --}}

	<div class="has-border-top">
		<span class="is-size-7">
			<span class="p-l-10">
				{{ $likesCount = $thread->likes_count }} {{ str_plural('Like', $likesCount) }}
			</span>
			<span class="p-l-10">
				{{ $thread->replies_count }} {{ str_plural('reply', $thread->replies_count) }}
			</span>
		</span>
	</div>
</div> {{-- end of main thread title and body --}}