routes/web.php
<?php

use Illuminate\Support\Facades\Mail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/reset-request-sent', 'UserController@resetRequestSent')->name('reset-request-sent');
Route::get('/reset-successful', 'UserController@resetSuccessful')
		->middleware('auth')->name('reset-successful');
Route::get('/register/confirm', 'Auth\RegisterConfirmationController@index')
		->name('register.confirm');

Route::get('/forum', 'ForumController@home')->name('forum.home');
Route::get('/forum/{section}', 'ForumController@section')->name('forum.section');
Route::get('/questions-home', 'QuestionsController@home')->name('questions.home');
Route::get('/questions-section/{section}', 'QuestionsController@section')->name('questions.section');
Route::get('/news-home', 'NewsController@home')->name('news.home');
Route::get('/section/{section}', 'NewsController@section')->name('section');

Route::get('/promo', 'PromoController@index')->name('promo.index');

//news routes
Route::get('/news/create', 'NewsController@create')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('news.create');
Route::post('/news', 'NewsController@store')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('news.store');
Route::get('/news', 'NewsController@index')->name('news.index');
Route::get('/news/trending', 'NewsController@trending')->name('news.trending');
Route::patch('/news/{news}', 'NewsController@update')
		->middleware('auth')->name('news.update');
Route::delete('/news/{news}', 'NewsController@destroy')->middleware('auth')->name('news.destroy');
Route::get('/news/{news}/edit', 'NewsController@edit')->middleware('auth')->name('news.edit');
Route::get('/news/{news}/comments', 'CommentController@index')->name('comments.index');
Route::post('/news/{news}/comments', 'CommentController@store')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('comments.store');
Route::post('/update-comments/{comment}', 'CommentController@update')
		->middleware('auth')->name('comments.update');
Route::delete('/comments/{comment}', 'CommentController@destroy')
		->middleware('auth')->name('comments.destroy');

Route::get('/news-report/{news}', 'NewsController@createReport')
		->middleware('auth')->name('news.report');
Route::get('/comments-report/{comment}', 'CommentController@createReport')
		->middleware('auth')->name('comments.report');

Route::get('/news/{news}/login', 'NewsController@loginToComment')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('news.login');
Route::get('/news/{news}/{slug}', 'NewsController@show')->name('news.show');

// statuses routes
Route::get('/statuses/{status}', 'StatusController@show')->name('statuses.show');
Route::post('/statuses', 'StatusController@store')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('statuses.store');
Route::patch('/statuses/{status}', 'StatusController@update')
		->middleware('auth')->name('statuses.update');
Route::delete('/statuses/{status}', 'StatusController@destroy')
		->middleware('auth')->name('statuses.destroy');
Route::get('/statuses/{status}/edit', 'StatusController@edit')
		->middleware('auth')->name('statuses.edit');
Route::get('/statuses/{status}/responses', 'ResponseController@index')->name('responses.index');
Route::post('/statuses/{status}/responses', 'ResponseController@store')
		->middleware('auth', 'user-not-banned')->name('responses.store');
Route::post('/update-responses/{response}', 'ResponseController@update')
		->middleware('auth')->name('responses.update');
Route::delete('/responses/{response}', 'ResponseController@destroy')
		->middleware('auth')->name('responses.destroy');

Route::get('/statuses-report/{status}', 'StatusController@createReport')
		->middleware('auth')->name('statuses.report');
Route::get('/responses-report/{response}', 'ResponseController@createReport')
		->middleware('auth')->name('responses.report');


Route::middleware('auth')->group(function() {
	//likes routes
	Route::post('/threads/{thread}/likes', 'LikeController@likeThread');
	Route::delete('/threads/{thread}/likes', 'LikeController@unlikeThread');
	Route::post('/threads/{thread}/dislikes', 'LikeController@dislikeThread');
	Route::delete('/threads/{thread}/dislikes', 'LikeController@undislikeThread');

	Route::post('/questions/{question}/likes', 'LikeController@likeQuestion');
	Route::delete('/questions/{question}/likes', 'LikeController@unlikeQuestion');
	Route::post('/questions/{question}/dislikes', 'LikeController@dislikeQuestion');
	Route::delete('/questions/{question}/dislikes', 'LikeController@undislikeQuestion');

	Route::post('/news/{news}/likes', 'LikeController@likeNews');
	Route::delete('/news/{news}/likes', 'LikeController@unlikeNews');
	Route::post('/news/{news}/dislikes', 'LikeController@dislikeNews');
	Route::delete('/news/{news}/dislikes', 'LikeController@undislikeNews');

	Route::post('/statuses/{status}/likes', 'LikeController@likeStatus');
	Route::delete('/statuses/{status}/likes', 'LikeController@unlikeStatus');
	Route::post('/statuses/{status}/dislikes', 'LikeController@dislikeStatus');
	Route::delete('/statuses/{status}/dislikes', 'LikeController@undislikeStatus');

	Route::post('/replies/{reply}/likes', 'LikeController@likeReply');
	Route::delete('/replies/{reply}/likes', 'LikeController@unlikeReply');
	Route::post('/replies/{reply}/dislikes', 'LikeController@dislikeReply');
	Route::delete('/replies/{reply}/dislikes', 'LikeController@undislikeReply');

	Route::post('/answers/{answer}/likes', 'LikeController@likeAnswer');
	Route::delete('/answers/{answer}/likes', 'LikeController@unlikeAnswer');
	Route::post('/answers/{answer}/dislikes', 'LikeController@dislikeAnswer');
	Route::delete('/answers/{answer}/dislikes', 'LikeController@undislikeAnswer');

	Route::post('/comments/{comment}/likes', 'LikeController@likeComment');
	Route::delete('/comments/{comment}/likes', 'LikeController@unlikeComment');
	Route::post('/comments/{comment}/dislikes', 'LikeController@dislikeComment');
	Route::delete('/comments/{comment}/dislikes', 'LikeController@undislikeComment');

	Route::post('/responses/{response}/likes', 'LikeController@likeResponse');
	Route::delete('/responses/{response}/likes', 'LikeController@unlikeResponse');
	Route::post('/responses/{response}/dislikes', 'LikeController@dislikeResponse');
	Route::delete('/responses/{response}/dislikes', 'LikeController@undislikeResponse');

	// subscription routes
	Route::post('/threads/{thread}/subscriptions', 'SubscriptionController@subscribeThread');
	Route::delete('/threads/{thread}/subscriptions', 'SubscriptionController@unsubscribeThread');

	Route::post('/questions/{question}/subscriptions', 'SubscriptionController@subscribeQuestion');
	Route::delete('/questions/{question}/subscriptions', 'SubscriptionController@unsubscribeQuestion');

	Route::post('/news/{news}/subscriptions', 'SubscriptionController@subscribeNews');
	Route::delete('/news/{news}/subscriptions', 'SubscriptionController@unsubscribeNews');

	// notification route
	Route::get('/notifications', 'UserNotificationController@allNotifications');
	Route::get('/delete-all-notifications', 'UserNotificationController@deleteAll')
			->name('delete.all.notifications');
	Route::delete('/notifications/{notification}', 'UserNotificationController@destroy');

	// appeal routes
	Route::get('/appeal', 'AppealController@index')->name('appeals.index');
	Route::get('/appeal/create', 'AppealController@create')->name('appeals.create');
	Route::post('/appeal', 'AppealController@store')->name('appeals.store');
	Route::delete('/appeal/{appeal}', 'AppealController@destroy')->name('appeals.destroy');

});


// report routes
Route::post('/report', 'ReportController@store')->middleware('auth')->name('reports.store');
Route::get('/report', 'ReportController@index')
	->middleware('auth', 'admin')->name('reports.index');
Route::delete('/report/{report}', 'ReportController@destroy')
	->middleware('auth', 'admin')->name('reports.destroy');
Route::post('report-blocked/{report}', 'ReportController@update')
	->middleware('auth', 'admin')->name('reports.blocked');

// management routes
Route::prefix('manage')
	->middleware('auth', 'admin')
	->group(function() {
	Route::get('/', 'ManageController@index')->name('manage.index');
	Route::get('/users', 'ManageUsersController@index')->name('manage.users');
	Route::get('/users/search', 'ManageUsersController@search')->name('manage.users.search');
	Route::get('/dashboard', 'ManageController@dashboard')->name('manage.dashboard');
	//sections routes
	Route::get('/sections', 'SectionsController@index')->name('sections.index');
	Route::post('/sections', 'SectionsController@store')->name('sections.store');
	Route::get('/sections/{section}/edit', 'SectionsController@edit')->name('sections.edit');
	Route::patch('/sections/{section}', 'SectionsController@update')->name('sections.update');
	Route::delete('/sections/{section}', 'SectionsController@destroy')->name('sections.destroy');
});
	
Route::middleware('auth', 'admin')
	->group(function() {
	//lock contents routes
	Route::post('/locked-threads/{thread}', 'LockedContentsController@lockThread')
			->name('locked-threads.store');
	Route::delete('/locked-threads/{thread}', 'LockedContentsController@unlockThread')
			->name('locked-threads.destroy');

	Route::post('/locked-questions/{question}', 'LockedContentsController@lockQuestion')
			->name('locked-questions.store');
	Route::delete('/locked-questions/{question}', 'LockedContentsController@unlockQuestion')
			->name('locked-questions.destroy');

app/Question.php
<?php

namespace App;

use App\Commonables;
use App\Events\QuestionReceivedNewAnswer;
use App\Likable;
use App\Notifications\QuestionWasUpdated;
use App\RecordsActivity;
use App\RecordsVisits;
use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
    use Likable, RecordsActivity, RecordsVisits, Commonables;

    /**
     * The relationships to always eager-load.
     *
     * @var array
     */
    protected $with = ['creator'];

    protected $fillable = [
        'user_id', 'section_id', 'title', 
        'slug', 'body', 'locked', 'pinned', 
        'blocked', 'featured_question', 'featured_home',
        'image1_path', 'image2_path', 'best_answer_id', 
        'sponsored_home', 'thumbnail_path'
    ];

    protected $appends = [
        'isLiked', 'isDisliked', 'isSubscribedTo', 
        'image1', 'image2', 'thumbnail'
    ];

    protected $casts = [
        'locked' => 'boolean',
        'blocked' => 'boolean',
        'pinned' => 'boolean',
        'featured_question' => 'boolean',
        'featured_home' => 'boolean'
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(function ($builder) {
            $builder->withCount('answers')
                ->withCount('likes')
                ->withCount('dislikes');
        });
        
        static::creating(function ($question) {
            Reputation::award($question->creator, Reputation::QUESTION_WAS_CREATED);
        });

        static::deleting(function ($question) {
            $question->answers->each->delete();

            Reputation::reduce($question->creator, Reputation::QUESTION_WAS_CREATED);
        });
    }
	
    public function path()
    {
    	return "/questions/{$this->id}";
    }

    public function showPath()
    {
        return "/questions/{$this->id}/{$this->slug}";
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function answers()
    {
        return $this->hasMany(Answer::class)->withCount('likes')->withCount('dislikes');
    }

    public function section()
    {
        return $this->belongsTo(Section::class);
    }

    public function bestAnswer()
    {
        return $this->belongsTo(Answer::class, 'best_answer_id');
    }

    public function addAnswer($answer)
    {
        $answer = $this->answers()->create($answer);

        // event to handle lot of things like sending
        // notification to thread subscribers and mentioned users
        event(new QuestionReceivedNewAnswer($answer));

        // notify question owner if others leave an answer
        if($answer->user_id != $this->user_id) {
            $this->creator->notify(new QuestionWasUpdated($this, $answer));
        }

        return $answer;
    }

    public function lock()
    {
        $this->update(['locked' => true]);
    }

    public function unlock()
    {
        $this->update(['locked' => false]);
    }

    public function block()
    {
        $this->update(['blocked' => true]);

        $this->update(['locked' => true]);
    }

    public function unblock()
    {
        $this->update(['blocked' => false]);

        $this->update(['locked' => false]);
    }

    public function featureQuestion()
    {
        $this->update(['featured_question' => true]);
    }

    public function unfeatureQuestion()
    {
        $this->update(['featured_question' => false]);
    }

    public function featureHome()
    {
        $this->update(['featured_home' => true]);
    }

    public function unfeatureHome()
    {
        $this->update(['featured_home' => false]);
    }

    public function sponsorHome()
    {
        $this->update(['sponsored_home' => true]);
    }

    public function unsponsorHome()
    {
        $this->update(['sponsored_home' => false]);
    }

    public function notifySubscribers($answer) 
    {
        foreach ($this->subscriptions as $subscription) {
            if ($subscription->user->id != $answer->user_id) {
                $subscription->user->notify(new QuestionWasUpdated($this, $answer));
            }
        }
    }

    public function scopeFilter($query, $filter)
    {
        return $filter->apply($query);
    }

    // subscriptions methods
    public function subscriptions()
    {
        return $this->morphMany(Subscription::class, 'subscribed');
    }

    public function subscribe()
    {
        $attributes = ['user_id' => auth()->id()];

        if (! $this->subscriptions()->where($attributes)->exists()) {
            $this->subscriptions()->create($attributes);
        }
    }

    public function unsubscribe()
    {
        $this->subscriptions()->where(['user_id' => auth()->id()])->get()->each->delete();
    }

    public function isSubscribedTo()
    {
        return $this->subscriptions()->where('user_id', auth()->id())->exists();
    }

    public function getIsSubscribedToAttribute()
    {
        return $this->isSubscribedTo();
    }


    public function hasUpdateFor()
    {
        $key = auth()->user()->visitedContentsCacheKey($this);

        if($this->answers()->exists()) {
            $lastAnswer = $this->answers()->latest()->first();
            if($lastAnswer->user_id != auth()->id()) {
                return $lastAnswer->updated_at > cache($key);
            }
        }
    }

    public function getBodyAttribute($body)
    {
        if($this->blocked) {
            return '<p style="color:red;">This Question has been blocked.</p>';
        }
        return \Purify::clean(ucfirst($body));
    }

}

resources/views/questions/_body_footer.blade.php
<div class="level is-marginless has-border-top-bottom p-5 is-size-7">
	<div class="level-left">
		<span class="p-l-20" v-text="likesCount">
			{{-- {{ $question->likes_count }} {{ str_plural('Like', $question->likes_count) }} --}}
		</span>
		<span class="p-l-20" v-text="dislikesCount"></span>
		<span class="p-l-20">
			<span v-text="answersCount"></span>
		</span>
	</div>	

	@include('partials.share_buttons', ['title' => $question->title])
</div>

@if(Auth()->check())
	<div class="level is-marginless p-5 is-size-6 has-border-bottom">
		<div class="level-left">
			<like :model="{{ $question }}" @liked="likeCounter"
				:model-route="'/questions/'"
				:like-type="'Like'"
				:dislike-type="'Dislike'">
			</like>
			<span v-if="isConfirmed" v-cloak>
				<a href="#newanswer-textarea" class="m-l-10 m-b-5 button is-small is-outlined is-link"><i class="fa fa-reply is-size-6 m-r-5"></i>Answer</a>
			</span>
		</div>
		<div class="level-right m-0">
			<subscribe-button 
				:data="{{ json_encode($question->isSubscribedTo) }}" 
				:modelpath="{{ json_encode($question->path()) }}"
				v-if="! authorize('owns', question)">
			</subscribe-button>
			<a href="{{ route('questions.report', $question) }}" class="button is-small is-danger is-outlined m-l-5">Report</a>
		</div>
	</div>

	@can('update', $question)
	<div class="level is-marginless p-5 is-size-6">
		<div class="level-left m-0 p-b-5">
			<admin-actions routename="questions/" 
				:model="{{ $question }}" 
				:featured="{{ json_encode($question->featured_question) }}">
			</admin-actions>
		</div>
		<div class="level-right m-0">
			<form method="POST" action="{{ route('questions.destroy', $question) }}" class="m-l-10">
				@csrf
				{{ method_field('DELETE') }}
				<a class="button is-small is-link is-outlined" href="{{ route('questions.edit', $question) }}">Edit</a>
				
				@include('partials.confirm_delete')
				
			</form>
		</div>
	</div>
	@endcan
@endif

resources/views/questions/_body_heading.blade.php
<h2 class="is-size-5 p-5 m-l-10 has-text-weight-bold has-text-centered" v-text="title"></h2>
<div class="media has-border-top-bottom p-5">
	<figure class="media-left">
		<p class="image is-32x32">
			<a href="{{ route('profile', $question->creator) }}">
				<img src="{{ $question->creator->thumbnail }}" class="profile-image-thumbnail-50x50" alt="">
			</a>
		</p>
	</figure>
	<div class="media-content">
		<div class="level is-marginless is-mobile">
			<div class="level-left">
				<span class="is-size-7">
					<strong>
						<a href="{{ route('profile', $question->creator) }}">
							{{ $question->creator->username }}
						</a> <span>({{ $question->creator->reputation }} xp)</span>
					</strong><br>
				</span>
			</div>
			<div class="level-right">
				<time datetime="{{ $question->created_at }}" class="is-size-7">
					<strong>{{ $question->created_at->diffForHumans() }}</strong>
				</time>
			</div>
		</div>
		<div class="level is-marginless is-mobile">
			<span class="is-size-7 m-r-5">
				<strong>
					{{ str_limit($question->creator->title, 50) }}
				</strong>
			</span>
			<div class="level-right">
				<span class="is-size-7">
					<strong>In: <a href="{{ route('questions.section', $question->section->slug) }}">{{ $question->section->name }}</a></strong>
				</span>
			</div>
		</div>
	</div>
</div> {{-- end of media --}}

resources/views/questions/body.blade.php
	{{-- SHOWING MAIN QUESTION--}}
<div class="has-border"> 
	{{-- main question heading --}}
	@include('questions._body_heading')

	<div class="p-10">
		<p class="has-text-centered" v-if="image1">
			<figure class="image">
				<img :src="image1" alt="">
			</figure>
		</p>

		<p class="is-size-6 m-b-15 m-t-15" v-html="body"></p>
		
		<p class="has-text-centered" v-if="image2">
			<figure class="image">
				<img :src="image2" alt="">
			</figure>
		</p>
	</div>
	{{-- main question footer --}}
	@include('questions._body_footer')

</div> {{-- end of main question title and body --}}

resources/views/questions/create.blade.php
@extends('layouts.app')

@section('title', 'NaijaNewsForum | Create Question')

@section('styles')
	<link href="{{ asset('css/vendor/trumbowyg.min.css') }}" rel="stylesheet">
	{{-- <link href="{{ asset('vendor/trumbowyg/dist/plugins/colors/ui/trumbowyg.colors.css') }}" rel="stylesheet"> --}}
@endsection

@section('content')
	<div class="box">
		
		<form method="POST" action="{{ route('questions.store') }}" enctype="multipart/form-data">
	        @csrf

	        <p class="is-size-4 has-text-centered is-underline">Ask New Question</p>
	        <p class="is-size-7 has-text-centered m-10">
	        	Please ensure you have read the Terms and Condition for Posting on this platform to avoid been banned. <br>
				<a class="is-underline" href="{{ route('terms') }}">Terms and Conditions</a>
	        </p>
	        
	        <div class="field">
	            <label for="title" class="label m-0">Question Title: </label>

	            <div class="control">
	            	<span class="is-size-7">Please start your question with How, What, Who, Why, When, Where, or Which.</span>
	                <input type="text" 
	                    class="input {{ $errors->has('title') ? ' is-danger' : '' }}" 
	                    id="title" name="title" maxlength="100"
	                    placeholder="Enter the title of your question here ..."
	                    value="{{ old('title') }}" required autofocus>

	                @if ($errors->has('title'))
	                    <p class="help is-danger">
	                        {{ $errors->first('title') }}
	                    </p>
	                @endif
	            </div>
	        </div>

	        <div class="field">
	            <label for="section" class="label m-0">Section: </label>
	            <div class="control">
	            	<span class="is-size-7">Please select appropriate section to get quick answers.</span>
					<div class="select {{ $errors->has('section') ? ' is-danger' : '' }}">
						<select name="section" required>
								<option value="" selected>Select appropriate section</option>
							@foreach($sections as $section)
								<option value="{{ $section->id }}" {{ old('section') == $section->id ? 'selected' : '' }}>
									{{ $section->name }}
								</option>
							@endforeach
						</select>
					</div>
	                @if ($errors->has('section'))
	                    <p class="help is-danger">
	                        {{ $errors->first('section') }}
	                    </p>
	                @endif
	            </div>
	        </div>

	        <div class="field">
	            <label for="body" class="label">Body of Question:</label>
	            <div class="control">
					<div id="create-textarea">
		                <textarea
		                    class="textarea {{ $errors->has('body') ? ' is-danger' : '' }}" 
		                    id="body" name="body" rows="1" 
		                    placeholder="Describe your question in detail here" required>
		                    {{ old('body') }}
		                </textarea>
		            </div>
	                    
	                @if ($errors->has('body'))
	                    <p class="help is-danger">
	                        {{ $errors->first('body') }}
	                    </p>
	                @endif
	            </div>
	        </div>

	        <div class="field">
				<p class="is-underline"><strong>Add Image</strong></p>
				<p class="is-size-7">
					<span class="is-red">NB: </span>Only jpg, jpeg, png, gif, svg images with max-size:4MB are allowed.
				</p>
				<div class="control">
					<label for="image1">Select Image 1.</label>
					<input type="file" name="image1" accept="image/*">
				</div>
				<div class="control">
					<label for="image2">Select Image 2.</label>
					<input type="file" name="image2" accept="image/*">
				</div>

				@if ($errors->has('image1'))
                    <p class="help is-danger">
                        {{ $errors->first('image1') }}
                    </p>
                @endif

                @if ($errors->has('image2'))
                    <p class="help is-danger">
                        {{ $errors->first('image2') }}
                    </p>
                @endif
			</div>

			<div class="field">
                <div class="control has-text-centered">
                    <label for="terms" class="is-size-7">
                        <input type="checkbox" class="checkbox" name="terms" required>
                            I accept that I will be solely responsible for this post and I shall be banned if this post violate the rules and regulations of this platform.
                    </label>
                </div>

                @if ($errors->has('terms'))
                    <p class="help is-danger">
                        {{ $errors->first('terms') }}
                    </p>
                @endif
            </div>

	        <div class="field">
	            <div class="control">
	                <button type="submit" class="button is-link">
	                    Post Question
	                </button>
	            </div>
	        </div>

	    </form>

	</div>
@endsection

@section('scripts')
	<script src="{{ asset('js/vendor/trumbowyg.min.js') }}"></script>
	
	{{-- Import Trumbowyg colors JS at the end of.. --}}
	{{-- <script src="{{ asset('vendor/trumbowyg/dist/plugins/colors/trumbowyg.colors.min.js') }}"></script> --}}

	<script>
		$('textarea').trumbowyg({
			autogrow: true,
			autogrowOnEnter: true,
			btns: [
				['strong', 'em', 'del'],
				['superscript', 'subscript'],
				// ['formatting'],
				// ['foreColor'],
				['link'],
				['insertImage'],
				['justifyLeft', 'justifyCenter', 'justifyRight', 'justifyFull'],
				// ['horizontalRule']
			]
		});
	</script>
@endsection

resources/views/questions/section_question.blade.php
	{{-- Main question title and body --}}
<div class="has-border m-b-20"> 
	<h2 class="is-size-5 p-5 m-l-10 is-darkgreen has-text-centered">
		<a class="is-darkgreen" href="{{ $question->showPath() }}">{{ $question->title }}</a>
	</h2>

	<div class="media has-border-top-bottom p-5">
		<figure class="media-left">
			<p class="image is-32x32">
				<a href="{{ route('profile', $question->creator) }}">
					<img src="{{ $question->creator->thumbnail }}" alt="">
				</a>
			</p>
		</figure>
		<div class="media-content">
			<div class="level is-mobile is-marginless">
				<div class="level-left">
					<span class="is-size-7">
						<strong>
							<a href="{{ route('profile', $question->creator) }}">
								{{ $question->creator->username }}
							</a> <span>({{ $question->creator->reputation }} xp)</span>
						</strong><br>
					</span>
				</div>
				<div class="level-right">
					<span class="is-size-7">
						<strong>{{ $question->created_at->diffForHumans() }}</strong>
					</span>
				</div>
			</div>
			<p>
				<span class="is-size-7">
					<strong>
						{{ str_limit($question->creator->title, 50) }}
					</strong>
				</span>
			</p>
		</div>
	</div> {{-- end of media --}}

	<div class="has-border-top">
		<span class="is-size-7">
			<span class="p-l-10">
				{{ $likesCount = $question->likes_count }} {{ str_plural('Like', $likesCount) }}
			</span>
			<span class="p-l-10">
				{{ $question->answers_count }} {{ str_plural('answer', $question->answers_count) }}
			</span>
		</span>
	</div>
</div> {{-- end of main question title and body --}}

resources/views/questions/subscription_question.blade.php
	{{-- Main thread title and body --}}
<div class="has-border m-b-20"> 
	@if($question->hasUpdateFor())
		<h1 class="is-size-5 has-text-justified p-5 m-l-10">
			<a class="is-darkgreen" href="{{ $question->showPath() }}">
				<strong>{{ $question->title }}</strong><i class="is-upated-note m-l-5">updated</i>
			</a>
		</h1>
	@else
		<h1 class="is-size-5 has-text-justified p-5 m-l-10">
			<a class="is-darkgreen" href="{{ $question->showPath() }}">{{ $question->title }}</a></h1>
	@endif

	<div class="media has-border-top-bottom p-5">
		<figure class="media-left">
			<p class="image is-32x32">
				<a href="{{ route('profile', $question->creator) }}">
					<img src="{{ $question->creator->thumbnail }}" alt="avatar">
				</a>
			</p>
		</figure>
		<div class="media-content">
			<div class="level is-mobile is-marginless">
				<div class="level-left">
					<span class="is-size-7">
						<strong>
							<a href="{{ route('profile', $question->creator) }}">
								{{ $question->creator->username }}
							</a> <span>({{ $question->creator->reputation }} xp)</span>
						</strong><br>
					</span>
				</div>
				<div class="level-right">
					<span class="is-size-7">
						<strong>{{ $question->created_at->diffForHumans() }}</strong>
					</span>
				</div>
			</div>
			<p>
				<span class="is-size-7">
					<strong>
						{{ str_limit($question->creator->title, 50) }}
					</strong>
				</span>
			</p>
		</div>
	</div> {{-- end of media --}}

	<div class="has-border-top">
		<span class="is-size-7">
			<span class="p-l-10">
				{{ $likesCount = $question->likes_count }} {{ str_plural('Like', $likesCount) }}
			</span>
			<span class="p-l-10">
				{{ $question->answers_count }} {{ str_plural('answer', $question->answers_count) }}
			</span>
		</span>
	</div>
</div> {{-- end of main question title and body --}}