routes/web.php
<?php

use Illuminate\Support\Facades\Mail;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/reset-request-sent', 'UserController@resetRequestSent')->name('reset-request-sent');
Route::get('/reset-successful', 'UserController@resetSuccessful')
		->middleware('auth')->name('reset-successful');
Route::get('/register/confirm', 'Auth\RegisterConfirmationController@index')
		->name('register.confirm');

Route::get('/forum', 'ForumController@home')->name('forum.home');
Route::get('/forum/{section}', 'ForumController@section')->name('forum.section');
Route::get('/questions-home', 'QuestionsController@home')->name('questions.home');
Route::get('/questions-section/{section}', 'QuestionsController@section')->name('questions.section');
Route::get('/news-home', 'NewsController@home')->name('news.home');
Route::get('/section/{section}', 'NewsController@section')->name('section');

Route::get('/promo', 'PromoController@index')->name('promo.index');

//news routes
Route::get('/news/create', 'NewsController@create')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('news.create');
Route::post('/news', 'NewsController@store')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('news.store');
Route::get('/news', 'NewsController@index')->name('news.index');
Route::get('/news/trending', 'NewsController@trending')->name('news.trending');
Route::patch('/news/{news}', 'NewsController@update')
		->middleware('auth')->name('news.update');
Route::delete('/news/{news}', 'NewsController@destroy')->middleware('auth')->name('news.destroy');
Route::get('/news/{news}/edit', 'NewsController@edit')->middleware('auth')->name('news.edit');
Route::get('/news/{news}/comments', 'CommentController@index')->name('comments.index');
Route::post('/news/{news}/comments', 'CommentController@store')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('comments.store');
Route::post('/update-comments/{comment}', 'CommentController@update')
		->middleware('auth')->name('comments.update');
Route::delete('/comments/{comment}', 'CommentController@destroy')
		->middleware('auth')->name('comments.destroy');

Route::get('/news-report/{news}', 'NewsController@createReport')
		->middleware('auth')->name('news.report');
Route::get('/comments-report/{comment}', 'CommentController@createReport')
		->middleware('auth')->name('comments.report');

Route::get('/news/{news}/login', 'NewsController@loginToComment')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('news.login');
Route::get('/news/{news}/{slug}', 'NewsController@show')->name('news.show');

// statuses routes
Route::get('/statuses/{status}', 'StatusController@show')->name('statuses.show');
Route::post('/statuses', 'StatusController@store')
		->middleware('auth', 'must-be-confirmed', 'user-not-banned')->name('statuses.store');
Route::patch('/statuses/{status}', 'StatusController@update')
		->middleware('auth')->name('statuses.update');
Route::delete('/statuses/{status}', 'StatusController@destroy')
		->middleware('auth')->name('statuses.destroy');
Route::get('/statuses/{status}/edit', 'StatusController@edit')
		->middleware('auth')->name('statuses.edit');
Route::get('/statuses/{status}/responses', 'ResponseController@index')->name('responses.index');
Route::post('/statuses/{status}/responses', 'ResponseController@store')
		->middleware('auth', 'user-not-banned')->name('responses.store');
Route::post('/update-responses/{response}', 'ResponseController@update')
		->middleware('auth')->name('responses.update');
Route::delete('/responses/{response}', 'ResponseController@destroy')
		->middleware('auth')->name('responses.destroy');

Route::get('/statuses-report/{status}', 'StatusController@createReport')
		->middleware('auth')->name('statuses.report');
Route::get('/responses-report/{response}', 'ResponseController@createReport')
		->middleware('auth')->name('responses.report');


Route::middleware('auth')->group(function() {
	//likes routes
	Route::post('/threads/{thread}/likes', 'LikeController@likeThread');
	Route::delete('/threads/{thread}/likes', 'LikeController@unlikeThread');
	Route::post('/threads/{thread}/dislikes', 'LikeController@dislikeThread');
	Route::delete('/threads/{thread}/dislikes', 'LikeController@undislikeThread');

	Route::post('/questions/{question}/likes', 'LikeController@likeQuestion');
	Route::delete('/questions/{question}/likes', 'LikeController@unlikeQuestion');
	Route::post('/questions/{question}/dislikes', 'LikeController@dislikeQuestion');
	Route::delete('/questions/{question}/dislikes', 'LikeController@undislikeQuestion');

	Route::post('/news/{news}/likes', 'LikeController@likeNews');
	Route::delete('/news/{news}/likes', 'LikeController@unlikeNews');
	Route::post('/news/{news}/dislikes', 'LikeController@dislikeNews');
	Route::delete('/news/{news}/dislikes', 'LikeController@undislikeNews');

	Route::post('/statuses/{status}/likes', 'LikeController@likeStatus');
	Route::delete('/statuses/{status}/likes', 'LikeController@unlikeStatus');
	Route::post('/statuses/{status}/dislikes', 'LikeController@dislikeStatus');
	Route::delete('/statuses/{status}/dislikes', 'LikeController@undislikeStatus');

	Route::post('/replies/{reply}/likes', 'LikeController@likeReply');
	Route::delete('/replies/{reply}/likes', 'LikeController@unlikeReply');
	Route::post('/replies/{reply}/dislikes', 'LikeController@dislikeReply');
	Route::delete('/replies/{reply}/dislikes', 'LikeController@undislikeReply');

	Route::post('/answers/{answer}/likes', 'LikeController@likeAnswer');
	Route::delete('/answers/{answer}/likes', 'LikeController@unlikeAnswer');
	Route::post('/answers/{answer}/dislikes', 'LikeController@dislikeAnswer');
	Route::delete('/answers/{answer}/dislikes', 'LikeController@undislikeAnswer');

	Route::post('/comments/{comment}/likes', 'LikeController@likeComment');
	Route::delete('/comments/{comment}/likes', 'LikeController@unlikeComment');
	Route::post('/comments/{comment}/dislikes', 'LikeController@dislikeComment');
	Route::delete('/comments/{comment}/dislikes', 'LikeController@undislikeComment');

	Route::post('/responses/{response}/likes', 'LikeController@likeResponse');
	Route::delete('/responses/{response}/likes', 'LikeController@unlikeResponse');
	Route::post('/responses/{response}/dislikes', 'LikeController@dislikeResponse');
	Route::delete('/responses/{response}/dislikes', 'LikeController@undislikeResponse');

	// subscription routes
	Route::post('/threads/{thread}/subscriptions', 'SubscriptionController@subscribeThread');
	Route::delete('/threads/{thread}/subscriptions', 'SubscriptionController@unsubscribeThread');

	Route::post('/questions/{question}/subscriptions', 'SubscriptionController@subscribeQuestion');
	Route::delete('/questions/{question}/subscriptions', 'SubscriptionController@unsubscribeQuestion');

	Route::post('/news/{news}/subscriptions', 'SubscriptionController@subscribeNews');
	Route::delete('/news/{news}/subscriptions', 'SubscriptionController@unsubscribeNews');

	// notification route
	Route::get('/notifications', 'UserNotificationController@allNotifications');
	Route::get('/delete-all-notifications', 'UserNotificationController@deleteAll')
			->name('delete.all.notifications');
	Route::delete('/notifications/{notification}', 'UserNotificationController@destroy');

	// appeal routes
	Route::get('/appeal', 'AppealController@index')->name('appeals.index');
	Route::get('/appeal/create', 'AppealController@create')->name('appeals.create');
	Route::post('/appeal', 'AppealController@store')->name('appeals.store');
	Route::delete('/appeal/{appeal}', 'AppealController@destroy')->name('appeals.destroy');

});


// report routes
Route::post('/report', 'ReportController@store')->middleware('auth')->name('reports.store');
Route::get('/report', 'ReportController@index')
	->middleware('auth', 'admin')->name('reports.index');
Route::delete('/report/{report}', 'ReportController@destroy')
	->middleware('auth', 'admin')->name('reports.destroy');
Route::post('report-blocked/{report}', 'ReportController@update')
	->middleware('auth', 'admin')->name('reports.blocked');

// management routes
Route::prefix('manage')
	->middleware('auth', 'admin')
	->group(function() {
	Route::get('/', 'ManageController@index')->name('manage.index');
	Route::get('/users', 'ManageUsersController@index')->name('manage.users');
	Route::get('/users/search', 'ManageUsersController@search')->name('manage.users.search');
	Route::get('/dashboard', 'ManageController@dashboard')->name('manage.dashboard');
	//sections routes
	Route::get('/sections', 'SectionsController@index')->name('sections.index');
	Route::post('/sections', 'SectionsController@store')->name('sections.store');
	Route::get('/sections/{section}/edit', 'SectionsController@edit')->name('sections.edit');
	Route::patch('/sections/{section}', 'SectionsController@update')->name('sections.update');
	Route::delete('/sections/{section}', 'SectionsController@destroy')->name('sections.destroy');
});
	
Route::middleware('auth', 'admin')
	->group(function() {
	//lock contents routes
	Route::post('/locked-threads/{thread}', 'LockedContentsController@lockThread')
			->name('locked-threads.store');
	Route::delete('/locked-threads/{thread}', 'LockedContentsController@unlockThread')
			->name('locked-threads.destroy');

	Route::post('/locked-questions/{question}', 'LockedContentsController@lockQuestion')
			->name('locked-questions.store');
	Route::delete('/locked-questions/{question}', 'LockedContentsController@unlockQuestion')
			->name('locked-questions.destroy');

app/Activity.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Activity extends Model
{
    protected $fillable = [
    	'user_id', 'subject_id', 'subject_type', 'type'
    ];

    protected $with = ['subject'];

    public function subject()
    {
    	return $this->morphTo();
    }

    public static function feed($user)
    {
    	return $user->activities()
    			->take(10)->latest()->get();
    }
}

app/News.php
<?php

namespace App;

use App\Comment;
use App\Commonables;
use App\Events\NewsReceivedNewComment;
use App\Notifications\NewsWasUpdated;
use App\Region;
use App\Section;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    use Likable, RecordsActivity, Commonables;

    /**
     * The relationships to always eager-load.
     *
     * @var array
     */
    protected $with = ['creator'];

    protected $fillable = [
        'user_id', 'section_id', 'title', 
        'slug', 'body', 'locked', 'pinned', 
        'blocked', 'featured_news', 'featured_home', 
        'image1_path', 'image2_path', 'region_id',
        'sponsored_home', 'thumbnail_path'
    ];

    protected $appends = [
        'isLiked', 'isDisliked', 'isSubscribedTo', 
        'image1', 'image2', 'thumbnail'
    ];

    protected $casts = [
        'locked' => 'boolean',
        'blocked' => 'boolean',
        'pinned' => 'boolean',
        'featured_news' => 'boolean',
        'featured_home' => 'boolean'
    ];

    protected static function boot()
    {
        parent::boot();

        static::addGlobalScope(function ($builder) {
            $builder->withCount('comments')
                ->withCount('likes')
                ->withCount('dislikes');
        });
        
        static::creating(function ($news) {
            Reputation::award($news->creator, Reputation::NEWS_WAS_CREATED);
        });

        static::deleting(function ($news) {
            $news->comments->each->delete();

            Reputation::reduce($news->creator, Reputation::NEWS_WAS_CREATED);
        });
    }
	
    public function path()
    {
    	return "/news/{$this->id}";
    }

    public function showPath()
    {
        return "/news/{$this->id}/{$this->slug}";
    }

    public function creator()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function comments()
    {
        return $this->hasMany(Comment::class)->withCount('likes')->withCount('dislikes');
    }

    public function section()
    {
        return $this->belongsTo(Section::class);
    }

    public function region()
    {
        return $this->belongsTo(Region::class);
    }

    public function addComment($comment)
    {
        $comment = $this->comments()->create($comment);

        // event to handle lot of things like sending
        // notification to thread subscribers and mentioned users
        event(new NewsReceivedNewComment($comment));

        // notify news owner if others leave an comment
        if($comment->user_id != $this->user_id) {
            $this->creator->notify(new NewsWasUpdated($this, $comment));
        }

        return $comment;
    }

    public function lock()
    {
        $this->update(['locked' => true]);
    }

    public function unlock()
    {
        $this->update(['locked' => false]);
    }

    public function block()
    {
        $this->update(['blocked' => true]);

        $this->update(['locked' => true]);
    }

    public function unblock()
    {
        $this->update(['blocked' => false]);

        $this->update(['locked' => false]);
    }

    public function featureNews()
    {
        $this->update(['featured_news' => true]);
    }

    public function unfeatureNews()
    {
        $this->update(['featured_news' => false]);
    }

    public function featureHome()
    {
        $this->update(['featured_home' => true]);
    }

    public function unfeatureHome()
    {
        $this->update(['featured_home' => false]);
    }

    public function sponsorHome()
    {
        $this->update(['sponsored_home' => true]);
    }

    public function unsponsorHome()
    {
        $this->update(['sponsored_home' => false]);
    }

    public function notifySubscribers($comment) 
    {
        foreach ($this->subscriptions as $subscription) {
            if ($subscription->user->id != $comment->user_id) {
                $subscription->user->notify(new NewsWasUpdated($this, $comment));
            }
        }
    }

    public function scopeFilter($query, $filter)
    {
        return $filter->apply($query);
    }

    // subscriptions methods
    public function subscriptions()
    {
        return $this->morphMany(Subscription::class, 'subscribed');
    }

    public function subscribe()
    {
        $attributes = ['user_id' => auth()->id()];

        if (! $this->subscriptions()->where($attributes)->exists()) {
            $this->subscriptions()->create($attributes);
        }
    }

    public function unsubscribe()
    {
        $this->subscriptions()->where(['user_id' => auth()->id()])->get()->each->delete();
    }

    public function isSubscribedTo()
    {
        return $this->subscriptions()->where('user_id', auth()->id())->exists();
    }

    public function getIsSubscribedToAttribute()
    {
        return $this->isSubscribedTo();
    }


    public function hasUpdateFor()
    {
        $key = auth()->user()->visitedContentsCacheKey($this);

        if($this->comments()->exists()) {
            $lastComment = $this->comments()->latest()->first();
            if($lastComment->user_id != auth()->id()) {
                return $lastComment->updated_at > cache($key);
            }
        }
    }

    // public function getRegionNameAttribute()
    // {
    //     if($this->region_id) {
    //         return $this->region()->first()->name;
    //     } else {
    //         return false;
    //     }
    // }

    public function getBodyAttribute($body)
    {
        if($this->blocked) {
            return '<p style="color:red;">This News has been blocked.</p>';
        }
        return \Purify::clean(ucfirst($body));
    }
}

resources/views/activities/created_news.blade.php
	{{-- Main activity title and body --}}
<div class="has-border m-b-20"> 
	<h2 class="is-size-5 has-text-centered p-5 m-l-10">
		<a class="is-darkgreen has-text-weight-semibold" href="{{ $activity->subject->showPath() }}">{{ $activity->subject->title }}</a>
	</h2>

	<div class="media has-border-top-bottom p-5">
		<figure class="media-left">
			<p class="image is-32x32">
				<a href="{{ route('profile', $activity->subject->creator) }}">
					<img src="{{ $activity->subject->creator->thumbnail }}" alt="">
				</a>
			</p>
		</figure>
		<div class="media-content">
			<div class="level is-mobile is-marginless">
				<div class="level-left">
					<span class="is-size-7">
						<strong>
							<a href="{{ route('profile', $activity->subject->creator) }}">
								{{ $activity->subject->creator->username }}
							</a> <span>({{ $activity->subject->creator->reputation }} xp)</span>
						</strong><br>
					</span>
				</div>
				<div class="level-right">
					<span class="is-size-7">
						<strong>{{ $activity->subject->created_at->diffForHumans() }}</strong>
					</span>
				</div>
			</div>
			<p>
				<span class="is-size-7">
					<strong>
						{{ str_limit($activity->subject->creator->title, 50) }}
					</strong>
				</span>
			</p>
		</div>
	</div> {{-- end of media --}}

	<div class="has-border-top">
		<span class="is-size-7">
			<span class="p-l-10">
				{{ $likesCount = $activity->subject->likes_count }} {{ str_plural('Truth', $likesCount) }}
			</span>
			<span class="p-l-10">
				{{ $likesCount = $activity->subject->dislikes_count }} {{ str_plural('False', $likesCount) }}
			</span>
			<span class="p-l-10">
				{{ $activity->subject->comments_count }} {{ str_plural('comment', $activity->subject->comments_count) }}
			</span>
		</span>
	</div>
</div> {{-- end of main activity title and body --}}

resources/views/activities/created_question.blade.php
	{{-- Main activity title and body --}}
<div class="has-border m-b-20"> 
	<h2 class="is-size-5 has-text-centered p-5 m-l-10">
		<a class="is-darkgreen has-text-weight-semibold" href="{{ $activity->subject->showPath() }}">{{ $activity->subject->title }}</a>
	</h2>

	<div class="media has-border-top-bottom p-5">
		<figure class="media-left">
			<p class="image is-32x32">
				<a href="{{ route('profile', $activity->subject->creator) }}">
					<img src="{{ $activity->subject->creator->thumbnail }}" alt="">
				</a>
			</p>
		</figure>
		<div class="media-content">
			<div class="level is-mobile is-marginless">
				<div class="level-left">
					<span class="is-size-7">
						<strong>
							<a href="{{ route('profile', $activity->subject->creator) }}">
								{{ $activity->subject->creator->username }}
							</a> <span>({{ $activity->subject->creator->reputation }} xp)</span>
						</strong><br>
					</span>
				</div>
				<div class="level-right">
					<span class="is-size-7">
						<strong>{{ $activity->subject->created_at->diffForHumans() }}</strong>
					</span>
				</div>
			</div>
			<p>
				<span class="is-size-7">
					<strong>
						{{ str_limit($activity->subject->creator->title, 50) }}
					</strong>
				</span>
			</p>
		</div>
	</div> {{-- end of media --}}

	<div class="has-border-top">
		<span class="is-size-7">
			<span class="p-l-10">
				{{ $likesCount = $activity->subject->likes_count }} {{ str_plural('Like', $likesCount) }}
			</span>
			<span class="p-l-10">
				{{ $likesCount = $activity->subject->dislikes_count }} {{ str_plural('Dislike', $likesCount) }}
			</span>
			<span class="p-l-10">
				{{ $activity->subject->answers_count }} {{ str_plural('answer', $activity->subject->answers_count) }}
			</span>
		</span>
	</div>
</div> {{-- end of main activity title and body --}}

resources/views/activities/created_status.blade.php
    {{-- Main activity title and body --}}
<div class="has-border m-b-20">
    <em class="m-l-20">
        {{ $activity->subject->creator->username }} recent status update
    </em>

    <div class="media has-border-top-bottom p-5">
        <figure class="media-left">
            <p class="image is-32x32">
                <a href="{{ route('profile', $activity->subject->creator) }}">
                    <img src="{{ $activity->subject->creator->thumbnail }}" alt="">
                </a>
            </p>
        </figure>
        <div class="media-content">
            <div class="level is-mobile is-marginless">
                <div class="level-left">
                    <span class="is-size-7">
                        <strong>
                            <a href="{{ route('profile', $activity->subject->creator) }}">
                                {{ $activity->subject->creator->username }}
                            </a> <span>({{ $activity->subject->creator->reputation }} xp)</span>
                        </strong>
                    </span>
                </div>
                <div class="level-right">
                    <span class="is-size-7">
                        <strong>{{ $activity->subject->created_at->diffForHumans() }}</strong>
                    </span>
                </div>
            </div>
            <p>
                <span class="is-size-7">
                    <strong>
                        {{ str_limit($activity->subject->creator->title, 50) }}
                    </strong>
                </span>
            </p>
        </div>
    </div> {{-- end of media --}}

    <div class="p-10 has-text-justified">
        <p>
            {!! str_limit(strip_tags($activity->subject->body, '<br/><br><p>'), 100, '') !!}
            @if(strlen(strip_tags($activity->subject->body, '<br/><br><p>')) > 100)
                <a href="{{ $activity->subject->showPath() }}" class="btn btn-primary is-size-7">
                    ...Continue Reading
                </a>
            @endif
        </p>
    </div>

    <div class="has-border-top">
        <span class="is-size-7">
            <span class="p-l-10">
                {{ $likesCount = $activity->subject->likes_count }} {{ str_plural('Like', $likesCount) }}
            </span>
            <span class="p-l-10">
                {{ $likesCount = $activity->subject->dislikes_count }} {{ str_plural('Dislike', $likesCount) }}
            </span>
            <span class="p-l-10">
                {{ $activity->subject->responses_count }} {{ str_plural('comment', $activity->subject->responses_count) }}
            </span>

            <a href="{{ $activity->subject->showPath() }}" class="m-l-20 btn btn-primary">
                ...go to status
            </a>
        </span>
    </div>
</div> {{-- end of main activity title and body --}}

resources/views/activities/created_thread.blade.php
	{{-- Main activity title and body --}}
<div class="has-border m-b-20"> 
	<h2 class="is-size-5 has-text-centered p-5 m-l-10">
		<a class="is-darkgreen has-text-weight-semibold" href="{{ $activity->subject->showPath() }}">{{ $activity->subject->title }}</a>
	</h2>

	<div class="media has-border-top-bottom p-5">
		<figure class="media-left">
			<p class="image is-32x32">
				<a href="{{ route('profile', $activity->subject->creator) }}">
					<img src="{{ $activity->subject->creator->thumbnail }}" alt="">
				</a>
			</p>
		</figure>
		<div class="media-content">
			<div class="level is-mobile is-marginless">
				<div class="level-left">
					<span class="is-size-7">
						<strong>
							<a href="{{ route('profile', $activity->subject->creator) }}">
								{{ $activity->subject->creator->username }}
							</a> <span>({{ $activity->subject->creator->reputation }} xp)</span>
						</strong><br>
					</span>
				</div>
				<div class="level-right">
					<span class="is-size-7">
						<strong>{{ $activity->subject->created_at->diffForHumans() }}</strong>
					</span>
				</div>
			</div>
			<p>
				<span class="is-size-7">
					<strong>
						{{ str_limit($activity->subject->creator->title, 50) }}
					</strong>
				</span>
			</p>
		</div>
	</div> {{-- end of media --}}

	{{-- <div class="p-10 has-text-justified">
		<p>
			{!! str_limit(strip_tags($activity->subject->body, '<br/><br><p>'), 100, '') !!}
			@if(strlen(strip_tags($activity->subject->body, '<br/><br><p>')) > 100)
				<a href="{{ $activity->subject->showPath() }}" class="btn btn-primary is-size-7">
					...Continue Reading
				</a>
			@endif
		</p>
	</div> --}}

	<div class="has-border-top">
		<span class="is-size-7">
			<span class="p-l-10">
				{{ $likesCount = $activity->subject->likes_count }} {{ str_plural('Like', $likesCount) }}
			</span>
			<span class="p-l-10">
				{{ $likesCount = $activity->subject->dislikes_count }} {{ str_plural('Dislike', $likesCount) }}
			</span>
			<span class="p-l-10">
				{{ $activity->subject->replies_count }} {{ str_plural('reply', $activity->subject->replies_count) }}
			</span>
		</span>
	</div>
</div> {{-- end of main activity title and body --}}